language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t grahamalytics/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true grahamalytics/docker-react npm run test -- --coverage